# Generated by Django 4.1.4 on 2022-12-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('foto_url', models.URLField()),
                ('tags', models.CharField(max_length=100, null=True)),
                ('github_url', models.URLField()),
            ],
            options={
                'db_table': 'Proyectos',
            },
        ),
    ]
